// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface MemeInterface {
    
    keyword:           string;
    template:          TemplateEnum;
    meme:              BaseMemeInterface;
    defaultFrameIndex: number;
    frames:            FrameInterface[];
}

export interface FrameInterface {
    type:        TypeEnum;
    x:           number;
    y:           number;
    w:           number;
    h:           number;
    a:           number;
    text?:       Text;
    background?: string;
    image?:      ImageInterface;
    css?:        string;
}

export interface ImageInterface {
    align: string;
    url?:  string;
}

export interface TextInterface {
    valign:       AlignEnum;
    halign:       AlignEnum;
    value:        string;
    color?:       string;
    shadow?:      string;
    strokeSize?:  string;
    strokeColor?: string;
    css?:         string;
}

export interface BaseMemeInterface {
    w:     number;
    h:     number;
    image: ImageInterface;
}

export enum AlignEnum {
    Center = "center",
    FlexEnd = "flex-end",
    FlexStart = "flex-start",
}

export enum TypeEnum {
    Image = "IMAGE",
    ImageOrText = "IMAGE_OR_TEXT",
}

export enum TemplateEnum {
    DefaultHTML = "default.html",
}
